/* ================================================================
   TEMPLATE PACK CONTENT — /public/downloads/*.pdf
   Plain data; build.mjs renders it to Letter-size PDFs via headless
   Chrome. Every pack carries the same disclaimer: template language
   for a practice to adapt with its own counsel, never legal advice.
   Block types: h (section label), p, ul, fields, check, sign, note.
   ================================================================ */

const SIGN_PARENT = {
  t: 'sign',
  rows: [
    ['Parent / guardian signature', 'Printed name', 'Date'],
    ['Relationship to client', 'Phone', 'Email'],
  ],
};

export const PACKS = [
  {
    file: 'aba-consent-packet-templates.pdf',
    pack: 'Consent & authorization templates',
    docs: [
      {
        title: 'Consent to Treatment & Service Agreement',
        purpose: 'Signed once, before the assessment, by a person with the legal authority to consent for the client.',
        blocks: [
          { t: 'fields', cols: 2, items: ['Client name', 'Date of birth', 'Parent / guardian completing this form', 'Relationship to client'] },
          { t: 'h', text: 'Consent to assess and treat' },
          { t: 'p', text: 'I request and authorize [PRACTICE NAME] to provide applied behavior analysis services to the client named above. I understand that services begin with an assessment conducted by a [BCBA / licensed behavior analyst], that the assessment produces a written treatment plan, and that services are delivered by behavior technicians under that analyst’s supervision.' },
          { t: 'p', text: 'I understand that the assessment and treatment plan are clinical recommendations, that the amount of service ultimately delivered may be limited by my health plan’s authorization, and that no specific outcome has been promised to me.' },
          { t: 'h', text: 'Authority to consent' },
          { t: 'p', text: 'I certify that I am the client’s parent, legal guardian, or otherwise legally authorized to consent to this client’s health care, and that no court order limits my authority to do so. If that changes, I will notify [PRACTICE NAME] in writing within [NUMBER] days and provide the documentation establishing who may consent.' },
          { t: 'h', text: 'Services, setting, and participation' },
          { t: 'p', text: 'Services will be delivered in the following setting(s): [HOME / CENTER / SCHOOL / COMMUNITY / TELEHEALTH]. I understand that caregiver participation is a clinical component of the program and that my health plan may require documentation of that participation to continue authorizing services.' },
          { t: 'h', text: 'Attendance and cancellation' },
          { t: 'p', text: 'Consistent attendance is required for the program to work and for authorizations to be maintained. I understand [PRACTICE NAME]’s attendance expectations, including that cancellations should be made at least [NUMBER] hours in advance where possible, and that repeated missed sessions may result in a change to the schedule or discharge from the program.' },
          { t: 'h', text: 'Billing and assignment of benefits' },
          { t: 'p', text: 'I authorize [PRACTICE NAME] to bill my health plan for services provided and to release the clinical information the plan requires to process authorizations and claims. I assign to [PRACTICE NAME] the benefits otherwise payable to me for these services, and I remain responsible for amounts my plan does not pay.' },
          { t: 'h', text: 'Withdrawing consent' },
          { t: 'p', text: 'I may withdraw this consent at any time by notifying [PRACTICE NAME] in writing. Withdrawal takes effect when received and does not apply to services already provided or to disclosures already made in reliance on it.' },
          SIGN_PARENT,
          { t: 'sign', rows: [['[PRACTICE NAME] representative', 'Title', 'Date']] },
        ],
      },
      {
        title: 'Acknowledgement of Privacy Practices',
        purpose: 'A one-page acknowledgement that the notice was provided. Acknowledgement only — never a condition of scheduling.',
        blocks: [
          { t: 'fields', cols: 2, items: ['Client name', 'Date of birth'] },
          { t: 'h', text: 'Acknowledgement' },
          { t: 'p', text: 'I acknowledge that I have been provided with a copy of the Notice of Privacy Practices of [PRACTICE NAME], which describes how health information about the client named above may be used and disclosed, and how I can get access to that information. I understand that [PRACTICE NAME] may update the notice and that the current version is available at [WEBSITE / LOCATION] or on request.' },
          SIGN_PARENT,
          { t: 'h', text: 'For staff use — if the acknowledgement was not obtained' },
          { t: 'p', text: 'Document the good-faith effort made to obtain this acknowledgement and why it was not obtained. Services are not withheld for a missing acknowledgement.' },
          { t: 'fields', cols: 1, items: ['Effort made and reason not obtained'] },
          { t: 'fields', cols: 2, items: ['Staff name', 'Date'] },
        ],
      },
      {
        title: 'Communication Consent — Email, Text, and Voicemail',
        purpose: 'Collected at first contact, before any automated reminder or follow-up runs. Keep the record of when and how it was given.',
        blocks: [
          { t: 'fields', cols: 2, items: ['Client name', 'Parent / guardian name', 'Mobile number for texts', 'Email address'] },
          { t: 'h', text: 'What we will send' },
          { t: 'p', text: 'With your permission, [PRACTICE NAME] will contact you about this client’s care: appointment reminders and scheduling, requests for documents needed to start or continue services, insurance and authorization updates, and occasional program announcements. Message frequency varies with what is happening in your child’s intake and care.' },
          { t: 'h', text: 'Choose how we may reach you' },
          { t: 'check', items: [
            'Text message (SMS/MMS) to the mobile number above',
            'Email to the address above',
            'Detailed voicemail at the number above (rather than a request to call back)',
            'Automated appointment reminders through our scheduling system',
          ] },
          { t: 'h', text: 'What you should know' },
          { t: 'ul', items: [
            'Email and text are not fully secure. Messages may be seen by anyone with access to your device or account, and information about your child’s care may appear in them.',
            'Standard message and data rates from your carrier may apply. [PRACTICE NAME] does not charge for these messages.',
            'You can stop text messages at any time by replying STOP, or get help by replying HELP. You can stop emails using the unsubscribe link or by telling us.',
            'You can change or withdraw this consent at any time by contacting us at [PHONE] or [EMAIL].',
            'Consenting to text messages is not a condition of receiving services. We will reach you another way if you prefer.',
          ] },
          SIGN_PARENT,
          { t: 'note', text: 'Practices sending automated texts in the United States also register their messaging campaign with the carriers (A2P 10DLC). The opt-in language above, the STOP/HELP instructions, and the record of when consent was given are what that registration asks you to keep.' },
        ],
      },
      {
        title: 'Financial Responsibility & Benefits Acknowledgement',
        purpose: 'Given after verification returns real numbers, not before. It puts the family’s actual cost-share in writing.',
        blocks: [
          { t: 'fields', cols: 2, items: ['Client name', 'Date of verification', 'Health plan', 'Member ID'] },
          { t: 'h', text: 'What verification found' },
          { t: 'fields', cols: 2, items: ['Network status', 'Deductible / amount met', 'Coinsurance or copay', 'Out-of-pocket maximum', 'Authorization required', 'Visit or hour limits'] },
          { t: 'h', text: 'Acknowledgement' },
          { t: 'p', text: 'I understand that the amounts above come from a benefits verification performed with my health plan on the date shown, that a verification is a quote of benefits and not a guarantee of payment, and that the plan determines what it will pay when a claim is processed. Eligibility, deductible status, and authorization requirements can change.' },
          { t: 'p', text: 'I understand I am responsible for deductibles, copays, coinsurance, and any services my plan does not cover, including services provided after an authorization expires or is denied. [PRACTICE NAME] will tell me before continuing services that my plan has stopped covering.' },
          { t: 'h', text: 'Private-pay rates and fees' },
          { t: 'fields', cols: 2, items: ['Assessment rate', 'Direct therapy rate (per hour or unit)', 'Supervision rate', 'Late-cancellation / no-show fee'] },
          { t: 'h', text: 'Other coverage' },
          { t: 'p', text: 'I have disclosed all health coverage this client has, including any secondary or supplemental plan and any coverage through another parent or guardian. I will notify [PRACTICE NAME] within [NUMBER] days of any change in coverage.' },
          SIGN_PARENT,
        ],
      },
      {
        title: 'Authorization to Use or Disclose Health Information',
        purpose: 'The release that lets you trade records with the diagnosing clinician, the pediatrician, the school, and other therapies. One per outside party.',
        blocks: [
          { t: 'fields', cols: 2, items: ['Client name', 'Date of birth'] },
          { t: 'h', text: 'Who may exchange information' },
          { t: 'p', text: 'I authorize [PRACTICE NAME] and the party named below to exchange the health information described below.' },
          { t: 'fields', cols: 2, items: ['Other party (person or organization)', 'Relationship / role', 'Address', 'Phone and fax'] },
          { t: 'h', text: 'Direction of the exchange' },
          { t: 'check', items: [
            'Release information from [PRACTICE NAME] to the party named above',
            'Obtain information from the party named above',
            'Both — exchange information in either direction for coordination of care',
          ] },
          { t: 'h', text: 'Information covered' },
          { t: 'check', items: [
            'Diagnostic evaluation and testing results',
            'Treatment plans, progress reports, and session data',
            'Referrals, orders, and prescriptions',
            'Educational records, including the IEP, IFSP, or 504 plan',
            'Records of other therapies (speech, occupational, physical)',
            'Other: ______________________________________________',
          ] },
          { t: 'h', text: 'Purpose, expiration, and your rights' },
          { t: 'p', text: 'Purpose of this authorization: [COORDINATION OF CARE / INSURANCE AUTHORIZATION / OTHER]. This authorization expires on [DATE] or [EVENT], and if no date is entered it expires [NUMBER] months from signature.' },
          { t: 'p', text: 'I may revoke this authorization at any time by writing to [PRACTICE NAME] at [ADDRESS]. Revocation does not apply to information already released in reliance on it. Treatment, payment, and enrollment are not conditioned on my signing, except where the information is needed to determine whether services can be authorized or paid. Information released may no longer be protected by federal privacy rules once it reaches the receiving party.' },
          { t: 'note', text: 'Some categories of information — mental health notes, substance use records, HIV status, genetic testing — carry extra rules that vary by state and may require a separate signature or initials. Have your compliance reviewer confirm what your state requires before using this form.' },
          SIGN_PARENT,
        ],
      },
    ],
  },

  {
    file: 'aba-records-request-templates.pdf',
    pack: 'Clinical records request templates',
    docs: [
      {
        title: 'Records Request — Diagnosing Clinician',
        purpose: 'The letter your team sends when the family does not have the evaluation. Send it with a signed release attached.',
        blocks: [
          { t: 'fields', cols: 2, items: ['Date', 'Our reference', 'To (clinic / clinician)', 'Fax or secure email', 'Client name', 'Client date of birth'] },
          { t: 'h', text: 'Letter' },
          { t: 'p', text: 'To the medical records department:' },
          { t: 'p', text: 'Our practice has been asked to provide applied behavior analysis services to the client named above. A signed authorization to release information is attached. We are requesting the following records for the purpose of establishing eligibility and preparing a request for authorization to the client’s health plan:' },
          { t: 'ul', items: [
            'The comprehensive diagnostic evaluation, including the diagnosing clinician’s name, credentials, and signature',
            'The date of the evaluation and the diagnostic instruments administered, with scores',
            'The diagnosis and severity level as documented',
            'Any written referral, order, or prescription for behavioral services',
            'Any related psychological, developmental, or speech and language testing',
          ] },
          { t: 'p', text: 'Please send records to [FAX NUMBER] or [SECURE EMAIL]. If any portion is unavailable, a note telling us so is genuinely useful — it tells us to stop waiting and to arrange the evaluation another way. Questions can go to [STAFF NAME] at [PHONE].' },
          { t: 'fields', cols: 2, items: ['Requested by', 'Title', 'Practice', 'Phone'] },
        ],
      },
      {
        title: 'Fax Cover Sheet',
        purpose: 'Records still move by fax in this field. Keep a cover sheet with a confidentiality notice on it.',
        blocks: [
          { t: 'fields', cols: 2, items: ['To', 'Fax number', 'From', 'Return fax', 'Date', 'Pages including this one', 'Re (client initials and DOB only)', 'Callback number'] },
          { t: 'h', text: 'Message' },
          { t: 'fields', cols: 1, items: ['', '', ''] },
          { t: 'h', text: 'Confidentiality notice' },
          { t: 'p', text: 'This transmission is intended only for the person or entity named above and may contain information that is confidential and protected by law. If you are not the intended recipient, any disclosure, copying, distribution, or action taken in reliance on it is prohibited. If you received this in error, please notify us immediately at [PHONE] and destroy the transmission.' },
          { t: 'note', text: 'Put only the minimum identifying information on a cover sheet. Client initials and date of birth are usually enough to route it.' },
        ],
      },
      {
        title: 'Referral & Order Request — Primary Care Physician',
        purpose: 'For the states and plans that gate the benefit on a physician referral or written order rather than the diagnosis.',
        blocks: [
          { t: 'fields', cols: 2, items: ['Date', 'To (physician / practice)', 'Fax or secure email', 'Client name', 'Client date of birth', 'Health plan'] },
          { t: 'h', text: 'Letter' },
          { t: 'p', text: 'Dear Dr. [NAME],' },
          { t: 'p', text: 'Your patient named above has been referred to our practice for applied behavior analysis services. The patient’s health plan requires a referral and written order from the treating physician before an authorization request can be submitted. A signed authorization to release information is attached.' },
          { t: 'p', text: 'Please complete and return the order below, along with the most recent diagnostic evaluation and any related testing in your records. Returning it promptly is the single thing that most shortens the wait before this child can start.' },
          { t: 'h', text: 'Order — to be completed by the physician' },
          { t: 'fields', cols: 2, items: ['Diagnosis and ICD-10 code', 'Date of diagnosis', 'Diagnosing clinician (if not you)', 'Instrument used, if known'] },
          { t: 'check', items: [
            'I refer this patient for an applied behavior analysis assessment and, if medically necessary, treatment.',
            'I have reviewed the patient’s history and consider these services medically necessary.',
            'A copy of the diagnostic evaluation is attached.',
          ] },
          { t: 'sign', rows: [['Physician signature', 'Printed name and credential', 'Date'], ['NPI', 'Practice', 'Phone']] },
        ],
      },
      {
        title: 'Diagnosis Confirmation — Short Form',
        purpose: 'For programs that accept a signed statement of the diagnosis in place of a full evaluation. Never a substitute where the plan asks for the evaluation itself.',
        blocks: [
          { t: 'fields', cols: 2, items: ['Client name', 'Date of birth'] },
          { t: 'h', text: 'Clinician statement' },
          { t: 'p', text: 'I am a [PHYSICIAN / LICENSED PSYCHOLOGIST / OTHER QUALIFIED PROFESSIONAL] licensed in [STATE]. I have evaluated the client named above and confirm the following diagnosis, established on the date shown, using the instrument and criteria indicated.' },
          { t: 'fields', cols: 2, items: ['Diagnosis and ICD-10 code', 'Date established', 'Instrument(s) administered', 'Severity level documented', 'Date most recently reconfirmed', 'Evaluation on file at'] },
          { t: 'p', text: 'I understand this statement may be submitted to the client’s health plan in support of a request for authorization of applied behavior analysis services.' },
          { t: 'sign', rows: [['Clinician signature', 'Printed name and credential', 'Date'], ['License number and state', 'NPI', 'Phone']] },
          { t: 'note', text: 'Recency windows differ by state and plan — six months in some programs, three to five years in others. Record the date the diagnosis was established and the date it was last reconfirmed, because a plan may accept one and not the other.' },
        ],
      },
    ],
  },

  {
    file: 'aba-consent-authority-templates.pdf',
    pack: 'Consent authority templates',
    docs: [
      {
        title: 'Consent Authority Attestation',
        purpose: 'Collected when a family reports two households, differing last names, or any court involvement — before anything is sent out for signature.',
        blocks: [
          { t: 'fields', cols: 2, items: ['Client name', 'Date of birth', 'Person completing this form', 'Relationship to client'] },
          { t: 'h', text: 'Household and custody status' },
          { t: 'check', items: [
            'The client’s parents live in the same household and both may consent.',
            'The client’s parents live separately. A custody order or parenting plan is in effect. A copy is attached.',
            'The client’s parents live separately. No court order is in effect.',
            'I am the client’s court-appointed guardian. A copy of the order is attached.',
            'The client is in the custody of a state agency. Agency information is recorded on the following page.',
          ] },
          { t: 'h', text: 'Attestation' },
          { t: 'p', text: 'I attest that I hold the legal authority to consent to health care for the client named above, that the documents I have provided are true and complete copies, and that no court order limits my authority to consent to or to receive records about this client’s care.' },
          { t: 'p', text: 'I understand [PRACTICE NAME] relies on this attestation in accepting consents and in deciding who may receive information about this client, and I will notify the practice in writing within [NUMBER] days if any of it changes.' },
          { t: 'h', text: 'Who else may receive information' },
          { t: 'fields', cols: 2, items: ['Name', 'Relationship', 'Name', 'Relationship'] },
          { t: 'note', text: 'A parent without decision-making authority may still be entitled to records in many states. Do not assume the custody order settles both questions — read what it says about each.' },
          SIGN_PARENT,
        ],
      },
      {
        title: 'Authorized Representative Designation',
        purpose: 'For when the person handling intake is not the parent or guardian — a grandparent, a family friend, or a care manager.',
        blocks: [
          { t: 'fields', cols: 2, items: ['Client name', 'Date of birth', 'Parent / guardian making this designation', 'Relationship to client'] },
          { t: 'h', text: 'Designation' },
          { t: 'p', text: 'I designate the person named below as my authorized representative for the client above, for the purposes I have checked. This designation does not transfer legal guardianship and does not authorize consent to treatment unless I have checked that box.' },
          { t: 'fields', cols: 2, items: ['Representative name', 'Relationship to client', 'Phone', 'Email'] },
          { t: 'h', text: 'Scope' },
          { t: 'check', items: [
            'Complete intake paperwork and provide documents on my behalf',
            'Speak with our health plan about eligibility, benefits, and authorizations',
            'Receive scheduling communication and coordinate appointments',
            'Receive clinical information and progress updates',
            'Consent to assessment and treatment on my behalf',
          ] },
          { t: 'h', text: 'Duration and revocation' },
          { t: 'p', text: 'This designation is effective from [DATE] until [DATE OR EVENT], and I may revoke it at any time in writing to [PRACTICE NAME]. Revocation does not apply to anything already done in reliance on it.' },
          SIGN_PARENT,
        ],
      },
      {
        title: 'Foster Care & Agency Consent Record',
        purpose: 'For a child in state custody, where the person calling is often not the person who can consent.',
        blocks: [
          { t: 'fields', cols: 2, items: ['Client name', 'Date of birth', 'Date of placement', 'Placement type'] },
          { t: 'h', text: 'Who holds consent authority' },
          { t: 'check', items: [
            'The placing agency holds authority to consent to health care.',
            'A parent retains authority to consent. Contact information recorded below.',
            'A court order governs consent. A copy is attached.',
            'The resource / foster parent may consent to routine care within limits described below.',
          ] },
          { t: 'fields', cols: 2, items: ['Agency', 'Case number', 'Caseworker name', 'Caseworker phone', 'Caseworker email', 'Supervisor (backup contact)'] },
          { t: 'h', text: 'Limits and instructions' },
          { t: 'fields', cols: 1, items: ['Limits on consent, records, or contact', '', ''] },
          { t: 'h', text: 'Resource / foster parent' },
          { t: 'fields', cols: 2, items: ['Name', 'Phone', 'Address', 'Email'] },
          { t: 'note', text: 'Placements change, sometimes without notice to the provider. Re-confirm the caseworker and the consent authority on a set cadence rather than only at intake.' },
          { t: 'sign', rows: [['Recorded by', 'Title', 'Date']] },
        ],
      },
    ],
  },

  {
    file: 'aba-setting-consent-templates.pdf',
    pack: 'Setting & delivery consent templates',
    docs: [
      {
        title: 'Telehealth Consent',
        purpose: 'A separate consent from the general consent to treat in most states. Shown only when telehealth is on the service list.',
        blocks: [
          { t: 'fields', cols: 2, items: ['Client name', 'Date of birth'] },
          { t: 'h', text: 'What telehealth means here' },
          { t: 'p', text: 'Some services for the client named above may be delivered by live video rather than in person — typically caregiver coaching, supervision, and assessment activities that can be conducted remotely. The clinician and the client are in different locations and communicate through a video platform.' },
          { t: 'h', text: 'What you should understand' },
          { t: 'ul', items: [
            'The same privacy protections apply to a telehealth session as to an in-person session.',
            'Technology can fail. If a connection drops, we will reach you at [PHONE] and reschedule or continue by another method.',
            'Video is not appropriate for every service or every session, and your clinician may recommend returning to in-person delivery.',
            'You may decline telehealth or stop it at any time without affecting your access to in-person services.',
            'Your health plan may cover telehealth differently from in-person services, and coverage rules change.',
            'You are responsible for finding a private space for the session and for your own internet connection.',
          ] },
          { t: 'h', text: 'Location and emergencies' },
          { t: 'p', text: 'I will tell my clinician where the client is physically located at the start of each session, and I understand this is required because licensure and coverage depend on it. I will provide a phone number where I can be reached during sessions and the address where the client will be, so that emergency services can be directed there if needed.' },
          { t: 'check', items: [
            'I consent to services delivered by telehealth.',
            'I decline telehealth and request in-person services only.',
          ] },
          SIGN_PARENT,
        ],
      },
      {
        title: 'Photo, Video & Recording Release',
        purpose: 'Separate opt-ins, never a condition of starting. Recording for clinical supervision is a different question from recording for marketing.',
        blocks: [
          { t: 'fields', cols: 2, items: ['Client name', 'Date of birth'] },
          { t: 'h', text: 'Permission by use — initial each one you allow' },
          { t: 'check', items: [
            'Recording sessions for clinical review and supervision by the treating team',
            'Recording for training internal staff, with identifying details limited to what training requires',
            'Photographs or video used in materials shown outside the practice, including on our website or social media',
            'Use of the client’s first name in materials shown outside the practice',
            'Recording of telehealth sessions',
          ] },
          { t: 'h', text: 'Terms' },
          { t: 'p', text: 'I understand that permission is separate for each use above and that declining any of them will not affect the client’s services in any way. Recordings made for clinical review are stored under [PRACTICE NAME]’s records policy and retained for [PERIOD].' },
          { t: 'p', text: 'I may revoke this release at any time in writing. Revocation applies going forward and does not reach materials already published or distributed.' },
          SIGN_PARENT,
        ],
      },
      {
        title: 'In-Home Services Safety & Access Agreement',
        purpose: 'In-home families only. Collected before the first visit, not after the technician arrives.',
        blocks: [
          { t: 'fields', cols: 2, items: ['Client name', 'Service address', 'Parent / guardian', 'Phone'] },
          { t: 'h', text: 'Access' },
          { t: 'fields', cols: 2, items: ['Entrance and parking instructions', 'Building or gate code', 'Adult present during sessions', 'Backup contact if no one answers'] },
          { t: 'h', text: 'The home environment' },
          { t: 'check', items: [
            'There are animals in the home. Type and arrangements: ____________________',
            'Someone smokes in the home during the hours sessions would occur.',
            'There are firearms in the home. I confirm they are stored locked and unloaded, separate from ammunition.',
            'Other adults or children are regularly present during session hours.',
            'A working smoke detector is present on the service floor.',
          ] },
          { t: 'h', text: 'Agreements' },
          { t: 'ul', items: [
            'A parent or another responsible adult will remain in the home for the whole session.',
            'A safe, reasonably quiet workspace will be available, with the television off during session time.',
            'Sessions may be ended early if conditions in the home make it unsafe to continue, and we will work with you before that affects the schedule.',
            'Session start and end may be verified electronically at the service location, as required for home and community services.',
          ] },
          SIGN_PARENT,
        ],
      },
      {
        title: 'Community Outing Permission',
        purpose: 'Community-based programming only. One standing permission, refreshed on the cadence you set.',
        blocks: [
          { t: 'fields', cols: 2, items: ['Client name', 'Date of birth'] },
          { t: 'h', text: 'Permission' },
          { t: 'p', text: 'I give permission for the client named above to take part in community-based sessions with [PRACTICE NAME] staff, at locations relevant to the treatment goals in the current plan — for example a store, park, library, or restaurant within [DISTANCE] of the service address.' },
          { t: 'h', text: 'Transportation' },
          { t: 'check', items: [
            'The client will be transported by a parent or guardian to and from community sessions.',
            'The client may be transported by [PRACTICE NAME] staff in a practice vehicle.',
            'The client may not be transported by staff under any circumstances.',
          ] },
          { t: 'h', text: 'Terms' },
          { t: 'p', text: 'I understand community sessions carry ordinary public-setting risks, that staff will maintain the supervision level described in the treatment plan, and that I will be contacted at [PHONE] if a session ends early. This permission is effective from [DATE] and is reviewed at least every [PERIOD].' },
          SIGN_PARENT,
        ],
      },
    ],
  },

  {
    file: 'aba-document-requirements-worksheet.pdf',
    pack: 'Document requirements worksheet',
    docs: [
      {
        title: 'Document Requirements Worksheet',
        purpose: 'One page per state you serve. Fill it in once and it becomes the rule set your intake form runs on.',
        blocks: [
          { t: 'fields', cols: 2, items: ['State', 'Payer or program', 'Reviewed by', 'Date reviewed'] },
          { t: 'h', text: 'The three gates' },
          { t: 'fields', cols: 1, items: [
            'Is an autism diagnosis required, or does something else open the benefit?',
            'Is an independent physician referral or written order required?',
            'How fresh must the evaluation be, and is the clock on the diagnosis date or the last reconfirmation?',
          ] },
          { t: 'h', text: 'Who may establish the diagnosis' },
          { t: 'fields', cols: 2, items: ['Accepted credentials', 'Required instruments', 'Screeners accepted?', 'Provisional diagnosis accepted?'] },
          { t: 'h', text: 'Documents that travel with the authorization request' },
          { t: 'check', items: [
            'Comprehensive diagnostic evaluation',
            'Physician referral or written order',
            'Standardized instrument scoring reports — which: ______________________',
            'IEP, IFSP, or 504 plan when the child is in school',
            'School hour counts',
            'Treatment plan dated within ______ days of submission',
            'Other: ______________________________________________',
          ] },
          { t: 'h', text: 'Age and program limits' },
          { t: 'fields', cols: 2, items: ['Age range covered', 'Hour or dollar limits', 'Lifetime caps', 'Reauthorization interval'] },
          { t: 'h', text: 'Sources checked' },
          { t: 'fields', cols: 1, items: ['', ''] },
        ],
      },
      {
        title: 'Conditional Rules Worksheet',
        purpose: 'Turn the requirements above into form logic. Each row is one condition your intake form should carry.',
        blocks: [
          { t: 'h', text: 'Rules' },
          { t: 'p', text: 'Write each rule as a fact you already hold and what it does to the packet. If a rule cannot be written this way, it is not yet specific enough to build.' },
          { t: 'rules', rows: 9 },
          { t: 'h', text: 'Recency clocks to track' },
          { t: 'p', text: 'For every clinical document your form accepts, record the date on the document itself — not the date it was uploaded — and the window it has to stay inside.' },
          { t: 'fields', cols: 2, items: ['Document', 'Window', 'Document', 'Window', 'Document', 'Window'] },
          { t: 'h', text: 'Fallbacks' },
          { t: 'p', text: 'For each required document, what happens when the family does not have it? Name the path, not the error message.' },
          { t: 'fields', cols: 1, items: ['', '', ''] },
        ],
      },
    ],
  },
];
